[package]
name = "vibestream-api"
version = "0.1.0"
edition = "2021"

[dependencies]
# API Framework
axum = { version = "0.7", features = ["multipart"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }
tokio = { version = "1.36", features = ["full"] }

# Database
sea-orm = { version = "0.12", features = [
  "sqlx-postgres",
  "runtime-tokio-native-tls",
  "macros",
] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls"] }

# Blockchain & Web3
ethers = { version = "2.0", features = ["ws"] }
web3 = "0.19"

# Serialization & Types
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error Handling
thiserror = "1.0"
anyhow = "1.0"

# Logging & Metrics
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Utils
dotenv = "0.15"
uuid = { version = "1.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Storage
aws-sdk-s3 = "1.16"
ipfs-api-backend-hyper = "0.6"

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.12"
