[workspace]
resolver = "2"
members = [
    "backend-core",
    "ethereum-service"
]

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.25", features = ["full"] }
