[package]
name = "solana-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.16.0"
solana-logger = "1.16.0"
anyhow = "1.0"
bs58 = "0.5.0"
tokio = { version = "1.14.1", features = ["full"] } 