//! OpenAPI Documentation Module
//! 
//! Complete OpenAPI 3.1.0 implementation for VibeStream API Gateway

use utoipa::{OpenApi, ToSchema};
use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use uuid::Uuid;

pub mod router;
pub mod paths;

/// Generate complete OpenAPI documentation
pub fn generate_openapi_spec() -> String {
    let spec = ApiDoc::openapi();
    serde_json::to_string_pretty(&spec).unwrap_or_else(|_| "{}".to_string())
}

// The openapi() method is automatically generated by the #[derive(OpenApi)] macro
// We don't need to implement it manually - the macro already does it

/// Generate OpenAPI specification JSON
pub fn generate_openapi_json() -> String {
    let spec = generate_openapi_spec();
    serde_json::to_string_pretty(&spec).unwrap_or_else(|_| "{}".to_string())
}

// =============================================================================
// SCHEMA DEFINITIONS
// =============================================================================

#[derive(Serialize, Deserialize, ToSchema)]
pub struct User {
    pub id: Uuid,
    pub username: String,
    pub email: String,
    pub display_name: Option<String>,
    pub bio: Option<String>,
    pub avatar_url: Option<String>,
    pub tier: String,
    pub role: String,
    pub is_verified: bool,
    pub is_active: bool,
    pub wallet_address: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct CreateUserRequest {
    pub email: String,
    pub username: String,
    pub password: String,
    pub confirm_password: String,
    pub display_name: Option<String>,
    pub bio: Option<String>,
    pub terms_accepted: bool,
    pub marketing_emails_consent: Option<bool>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct LoginRequest {
    pub credential: String,
    pub password: String,
    pub remember_me: Option<bool>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct LoginResponse {
    pub token: String,
    pub user: User,
    pub expires_at: DateTime<Utc>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct Song {
    pub id: Uuid,
    pub title: String,
    pub artist_id: Uuid,
    pub duration_seconds: i32,
    pub genre: Option<String>,
    pub ipfs_hash: Option<String>,
    pub cover_art_url: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct CreateSongRequest {
    pub title: String,
    pub artist_id: Uuid,
    pub duration_seconds: i32,
    pub genre: Option<String>,
    pub audio_file: String,
    pub cover_art: Option<String>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct SongListResponse {
    pub songs: Vec<Song>,
    pub total: usize,
    pub limit: usize,
    pub offset: usize,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct Album {
    pub album_id: Uuid,
    pub title: String,
    pub artist_id: Uuid,
    pub description: Option<String>,
    pub release_date: Option<DateTime<Utc>>,
    pub song_count: u32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct AlbumListResponse {
    pub albums: Vec<Album>,
    pub total: usize,
    pub limit: usize,
    pub offset: usize,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct CreateAlbumRequest {
    pub title: String,
    pub artist_id: Uuid,
    pub description: Option<String>,
    pub release_date: Option<DateTime<Utc>>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct UpdateAlbumRequest {
    pub title: Option<String>,
    pub description: Option<String>,
    pub release_date: Option<DateTime<Utc>>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct Playlist {
    pub playlist_id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub is_public: bool,
    pub song_count: u32,
    pub created_by: Uuid,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct PlaylistListResponse {
    pub playlists: Vec<Playlist>,
    pub total: usize,
    pub limit: usize,
    pub offset: usize,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct CreatePlaylistRequest {
    pub name: String,
    pub description: Option<String>,
    pub is_public: bool,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct AddSongToPlaylistRequest {
    pub song_id: Uuid,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct Campaign {
    pub id: Uuid,
    pub name: String,
    pub description: String,
    pub campaign_type: String,
    pub song_id: Uuid,
    pub artist_id: Uuid,
    pub budget: f64,
    pub currency: String,
    pub start_date: DateTime<Utc>,
    pub end_date: DateTime<Utc>,
    pub status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct FanLoyaltyVerification {
    pub fan_id: Uuid,
    pub is_verified: bool,
    pub confidence_score: f64,
    pub verification_id: String,
    pub wristband_eligible: bool,
    pub benefits_unlocked: Vec<String>,
    pub created_at: DateTime<Utc>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct NftWristband {
    pub id: Uuid,
    pub fan_id: Uuid,
    pub wristband_type: String,
    pub token_id: String,
    pub contract_address: String,
    pub is_active: bool,
    pub created_at: DateTime<Utc>,
    pub activated_at: Option<DateTime<Utc>>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct QrCode {
    pub id: Uuid,
    pub wristband_id: Uuid,
    pub code: String,
    pub is_valid: bool,
    pub expires_at: DateTime<Utc>,
    pub created_at: DateTime<Utc>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct ApiError {
    pub code: String,
    pub message: String,
    pub details: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, ToSchema)]
pub struct ApiResponse<T> {
    pub success: bool,
    pub data: Option<T>,
    pub message: String,
    pub errors: Option<Vec<String>>,
}

// =============================================================================
// OPENAPI DOCUMENTATION
// =============================================================================

#[derive(OpenApi)]
#[openapi(
    paths(
        // User endpoints - Real handlers with utoipa annotations
        crate::bounded_contexts::user::presentation::controllers::user_controller::register_user,
        crate::bounded_contexts::user::presentation::controllers::user_controller::login_user,
        crate::bounded_contexts::user::presentation::controllers::user_controller::refresh_token,
        crate::bounded_contexts::user::presentation::controllers::user_controller::get_user_profile,
        // Music endpoints - Placeholder functions (handlers are in impl blocks, so we use placeholders)
        paths::_get_songs_doc,
        paths::_create_song_doc,
        paths::_get_song_doc,
        paths::_update_song_doc,
        paths::_delete_song_doc,
        // Albums and Playlists endpoints
        paths::_get_albums_doc,
        paths::_create_album_doc,
        paths::_get_album_doc,
        paths::_update_album_doc,
        paths::_delete_album_doc,
        paths::_get_playlists_doc,
        paths::_create_playlist_doc,
        paths::_get_playlist_doc,
        paths::_add_song_to_playlist_doc,
        paths::_remove_song_from_playlist_doc,
        // Campaign endpoints
        paths::_create_campaign_doc,
        // Payment endpoints
        crate::bounded_contexts::payment::presentation::controllers::PaymentController::initiate_payment,
        crate::bounded_contexts::payment::presentation::controllers::PaymentController::process_payment,
        crate::bounded_contexts::payment::presentation::controllers::PaymentController::get_payment,
        crate::bounded_contexts::payment::presentation::controllers::PaymentController::complete_payment,
        crate::bounded_contexts::payment::presentation::controllers::PaymentController::cancel_payment,
        crate::bounded_contexts::payment::presentation::controllers::PaymentController::initiate_refund,
        // Fan Loyalty endpoints
        crate::bounded_contexts::fan_loyalty::infrastructure::api_handlers::verify_fan_handler,
        crate::bounded_contexts::fan_loyalty::infrastructure::api_handlers::create_wristband_handler,
        crate::bounded_contexts::fan_loyalty::infrastructure::api_handlers::activate_wristband_handler,
        crate::bounded_contexts::fan_loyalty::infrastructure::api_handlers::get_wristband_handler,
        crate::bounded_contexts::fan_loyalty::infrastructure::api_handlers::generate_qr_code_handler,
        crate::bounded_contexts::fan_loyalty::infrastructure::api_handlers::validate_qr_code_handler,
        crate::bounded_contexts::fan_loyalty::infrastructure::api_handlers::get_fan_verification_handler,
        // Listen Rewards endpoints
        crate::bounded_contexts::listen_reward::presentation::handlers::start_listen_session,
        crate::bounded_contexts::listen_reward::presentation::handlers::complete_listen_session,
        crate::bounded_contexts::listen_reward::presentation::handlers::get_user_rewards,
        crate::bounded_contexts::listen_reward::presentation::handlers::distribute_rewards,
        crate::bounded_contexts::listen_reward::presentation::handlers::get_listen_analytics,
        // Fan Ventures endpoints
        crate::bounded_contexts::fan_ventures::presentation::venture_handlers::create_venture,
        crate::bounded_contexts::fan_ventures::presentation::venture_handlers::list_ventures,
        crate::bounded_contexts::fan_ventures::presentation::venture_handlers::get_venture_details,
        crate::bounded_contexts::fan_ventures::presentation::venture_handlers::update_venture,
        crate::bounded_contexts::fan_ventures::presentation::venture_handlers::delete_venture,
        crate::bounded_contexts::fan_ventures::presentation::venture_handlers::invest_in_venture,
        crate::bounded_contexts::fan_ventures::presentation::venture_handlers::get_user_portfolio,
        crate::bounded_contexts::fan_ventures::presentation::venture_handlers::get_artist_ventures
    ),
    components(
        schemas(
            User,
            CreateUserRequest,
            LoginRequest,
            LoginResponse,
            Song,
            CreateSongRequest,
            SongListResponse,
            Album,
            AlbumListResponse,
            CreateAlbumRequest,
            UpdateAlbumRequest,
            Playlist,
            PlaylistListResponse,
            CreatePlaylistRequest,
            AddSongToPlaylistRequest,
            Campaign,
            FanLoyaltyVerification,
            NftWristband,
            QrCode,
            ApiError,
            ApiResponse<serde_json::Value>,
            paths::RefreshTokenRequest,

            paths::RefreshTokenResponse,
            // Payment Schemas
            crate::bounded_contexts::payment::application::dto::PaymentDTO,
            crate::bounded_contexts::payment::application::dto::AmountDTO,
            crate::bounded_contexts::payment::application::dto::PaymentMethodDTO,
            crate::bounded_contexts::payment::application::dto::PaymentPurposeDTO,
            crate::bounded_contexts::payment::application::dto::InitiatePaymentRequest,
            crate::bounded_contexts::payment::application::dto::InitiatePaymentResponse,
            crate::bounded_contexts::payment::application::dto::ProcessPaymentRequest,
            // Listen Reward Schemas
            crate::bounded_contexts::listen_reward::presentation::handlers::StartListenSessionRequest,
            crate::bounded_contexts::listen_reward::presentation::handlers::StartListenSessionResponse,
            crate::bounded_contexts::listen_reward::presentation::handlers::CompleteListenSessionRequest,
            crate::bounded_contexts::listen_reward::presentation::handlers::CompleteListenSessionResponse,
            crate::bounded_contexts::listen_reward::presentation::handlers::UserRewardsResponse,
            crate::bounded_contexts::listen_reward::presentation::handlers::DistributeRewardsRequest,
            crate::bounded_contexts::listen_reward::presentation::handlers::DistributeRewardsResponse,
            crate::bounded_contexts::listen_reward::presentation::handlers::AnalyticsResponse,
            crate::bounded_contexts::listen_reward::presentation::handlers::DeviceInfo,
            // Fan Ventures Schemas
            crate::bounded_contexts::fan_ventures::presentation::venture_handlers::CreateVentureRequest,
            crate::bounded_contexts::fan_ventures::presentation::venture_handlers::CreateVentureResponse,
            crate::bounded_contexts::fan_ventures::presentation::venture_handlers::UpdateVentureRequest,
            crate::bounded_contexts::fan_ventures::presentation::venture_handlers::InvestInVentureRequest,
            crate::bounded_contexts::fan_ventures::presentation::venture_handlers::InvestInVentureResponse,
            crate::bounded_contexts::fan_ventures::presentation::venture_handlers::VentureDetailsResponse,
            crate::bounded_contexts::fan_ventures::presentation::venture_handlers::ListVenturesResponse,
            crate::bounded_contexts::fan_ventures::presentation::venture_handlers::VentureSummary,
            crate::bounded_contexts::fan_ventures::presentation::venture_handlers::UserPortfolioResponse,
            crate::bounded_contexts::fan_ventures::presentation::venture_handlers::PortfolioInvestment,
            crate::bounded_contexts::listen_reward::presentation::handlers::Location,
            crate::bounded_contexts::listen_reward::presentation::handlers::EngagementMetrics,
            crate::bounded_contexts::listen_reward::presentation::handlers::RewardBreakdown,
            crate::bounded_contexts::listen_reward::presentation::handlers::TierProgress,
            crate::bounded_contexts::listen_reward::presentation::handlers::TierBenefits,
            crate::bounded_contexts::listen_reward::presentation::handlers::Achievement,
            crate::bounded_contexts::listen_reward::presentation::handlers::SessionSummary,
            crate::bounded_contexts::listen_reward::presentation::handlers::UserStatistics,
            crate::bounded_contexts::listen_reward::presentation::handlers::BonusMultipliers,
            crate::bounded_contexts::listen_reward::presentation::handlers::TopEarner,
            crate::bounded_contexts::listen_reward::presentation::handlers::DistributionStats,
            crate::bounded_contexts::listen_reward::presentation::handlers::QualityDistribution,
            crate::bounded_contexts::listen_reward::presentation::handlers::TierDistribution,
            crate::bounded_contexts::listen_reward::presentation::handlers::SongPerformance,
            crate::bounded_contexts::listen_reward::presentation::handlers::FraudDetectionStats
        )
    ),
    tags(
        (name = "users", description = "User management and authentication"),
        (name = "music", description = "Music streaming and management"),
        (name = "campaigns", description = "Marketing campaigns and NFTs"),
        (name = "fan-loyalty", description = "Fan loyalty and biometric verification"),
        (name = "fan-ventures", description = "Fan investment platform"),
        (name = "notifications", description = "User notifications"),
        (name = "listen-rewards", description = "Listen tracking and rewards"),
        (name = "payments", description = "Payment processing")
    ),
    info(
        title = "VibeStream API",
        version = "1.0.0",
        description = "Complete VibeStream ecosystem API with microservices architecture",
        contact(
            name = "VibeStream Team",
            email = "api@vibestream.com"
        ),
        license(
            name = "MIT",
            url = "https://opensource.org/licenses/MIT"
        )
    ),
    servers(
        (url = "http://localhost:3000/api/v1", description = "Unified API Gateway - All endpoints use /api/v1 prefix")
    )
)]
pub struct ApiDoc;

/// Función para validar que todos los endpoints estén documentados
pub fn validate_api_coverage() -> Result<(), Vec<String>> {
    let mut missing_endpoints = Vec::new();
    
    // Lista de endpoints que deberían estar documentados
    let expected_endpoints = vec![
        // User Management
        "POST /api/v1/users/register",
        "POST /api/v1/users/login",
        "GET /api/v1/users/{id}",
        "PUT /api/v1/users/{id}",
        "DELETE /api/v1/users/{id}",
        "GET /api/v1/users/search",
        
        // Music Management
        "POST /api/v1/music/songs",
        "GET /api/v1/music/songs/{id}",
        "GET /api/v1/music/songs/search",
        "PUT /api/v1/music/songs/{id}",
        "DELETE /api/v1/music/songs/{id}",
        
        // Campaign Management
        "POST /api/v1/campaigns",
        "GET /api/v1/campaigns/{id}",
        "PUT /api/v1/campaigns/{id}/activate",
        "POST /api/v1/campaigns/{id}/purchase-nft",
        "GET /api/v1/campaigns/{id}/analytics",
        
        // Fan Loyalty System
        "POST /api/v1/fan-loyalty/verify",
        "POST /api/v1/fan-loyalty/wristbands",
        "GET /api/v1/fan-loyalty/wristbands/{id}",
        "POST /api/v1/fan-loyalty/wristbands/{id}/activate",
        "GET /api/v1/fan-loyalty/validate-qr/{code}",
        
        // Fan Ventures
        "POST /api/v1/fan-ventures/ventures",
        "GET /api/v1/fan-ventures/ventures/{id}",
        "POST /api/v1/fan-ventures/investments",
        "GET /api/v1/fan-ventures/portfolios/{user_id}",
        
        // Listen Rewards
        "POST /api/v1/listen-rewards/sessions",
        "PUT /api/v1/listen-rewards/sessions/{id}/complete",
        "POST /api/v1/listen-rewards/distribute",
        
        // Notifications
        "GET /api/v1/notifications/{user_id}",
        "POST /api/v1/notifications/send",
        "PUT /api/v1/notifications/{id}/read",
        
        // Payments
        "POST /api/v1/payments/process",
        "GET /api/v1/payments/{id}/status",
        "POST /api/v1/payments/refund",
        
        // Health Checks
        "GET /health",
        "GET /info",
    ];
    
    // Verificar que todos los endpoints estén implementados
    for endpoint in expected_endpoints {
        // Aquí podrías implementar lógica para verificar que el endpoint
        // esté realmente implementado en la aplicación
        // Por ahora, asumimos que todos están implementados
    }
    
    if missing_endpoints.is_empty() {
        Ok(())
    } else {
        Err(missing_endpoints)
    }
}

// Utilidades para generar documentación
pub mod utils {
    use super::*;
    use serde::Serialize;
    
    /// Genera un ejemplo de request para testing
    pub fn generate_request_example<T: Serialize>(data: &T) -> String {
        serde_json::to_string_pretty(data).unwrap_or_else(|_| "{}".to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_openapi_generation() {
        let spec = generate_openapi_spec();
        assert_eq!(spec.info.title, "VibeStream API");
        assert_eq!(spec.info.version, "1.0.0");
    }
    
    #[test]
    fn test_openapi_json_generation() {
        let json = generate_openapi_json();
        assert!(json.contains("VibeStream API"));
        assert!(json.contains("1.0.0"));
        
        // Write to file for client generation
        use std::io::Write;
        let mut file = std::fs::File::create("openapi.json").expect("Failed to create openapi.json");
        file.write_all(json.as_bytes()).expect("Failed to write to openapi.json");
    }
    
    #[test]
    fn test_api_coverage_validation() {
        let result = validate_api_coverage();
        assert!(result.is_ok());
    }
} 